default_install_hook_types: [pre-commit, pre-push]
repos:
  # Standard pre-commit hooks for file validation and basic quality
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # File validation
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-added-large-files
        args: ['--maxkb=100']
      - id: check-symlinks
      - id: check-illegal-windows-names
      - id: pretty-format-json
        args: ['--autofix']
      - id: sort-simple-yaml

      # Code quality (general)
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: fix-byte-order-marker

      # Security
      - id: detect-private-key
      - id: detect-aws-credentials
        args: ['--allow-missing-credentials']

      # File permissions and scripts
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable

  # Markdown linting
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.18.1
    hooks:
    - id: markdownlint-cli2

  # Typo checking
  - repo: https://github.com/crate-ci/typos
    rev: v1.35.5
    hooks:
      - id: typos
